### ISSUE TITLE
Preview of a post in netlifycms broken

### ISSUE THREAD

**Issue by psandtner** [danurbanowicz/eleventy-netlify-boilerplate#22] opened 2019-11-08 11:13 UTC
Without any change on my side since a few days/weeks ago there is the following error in Safari-Console:

`Failed to load resource: Cross-origin redirection to https://unpkg.com/htm@2.2.1/dist/htm.module.js?module denied by Cross-Origin Resource Sharing policy: Origin https://www.domainnamechangedforthisissue.de is not allowed by Access-Control-Allow-Origin. https://www.domainnamechangedforthisissue.de/.netlify/git/github/contents/.gitattributes?ts=1573207213206&ref=master`

Is this a unpkg.com-related problem? I’m a bit lost and cannot find any pointers to this...

**Comment by danurbanowicz** [comment] 2019-11-08 16:37
Have you tested this by deploying the demo site to Netlify to see if it happens? I'm unable to reproduce this error.

https://app.netlify.com/start/deploy?repository=https://github.com/danurbanowicz/eleventy-netlify-boilerplate&stack=cms

Please provide more info if you can and I'll have a closer look.

**Comment by psandtner** [comment] 2019-11-08 17:08
Yes, I just tested with a fresh deployment. Hm... I can provide you with some screenshots to show how it looks like.

<img width="1169" alt="edit_article_preview" src="https://user-images.githubusercontent.com/1395629/68496470-ba09ce00-0252-11ea-8f24-3c10f95f5d77.png">
<img width="863" alt="safari_console" src="https://user-images.githubusercontent.com/1395629/68496479-be35eb80-0252-11ea-92bb-9fee23a50409.png">

Thanks for you help!

**Comment by danurbanowicz** [comment] 2019-11-10 15:01
The CORS error is probably specific to your version of Safari, as I'm unable to replicate it with any of my browsers. And as I didn't do the post preview templates PR myself, I'm unfamiliar with how it's been built.

Not sure if this will work, but if you're interested in investigating this yourself, you could try implementing [Netlify's proxy redirecting](https://docs.netlify.com/routing/redirects/rewrites-proxies/#proxy-to-another-service) by adding something like the following in your `netlify.toml` to proxy requests for those unpkg modules through Netlify, thereby - in theory - bypassing the CORS policy on unpkg.com

```
[[redirects]]
  from = "/unpkg/*"
  to = "https://unpkg.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
```

The final 2 errors in your screenshot are caused by Netlify CMS looking for Git Large File Storage settings and these errors, although a bit worrying, are [apparently normal](https://community.netlify.com/t/failed-to-load-resource-errors-in-netlify-cms-admin-panel/929).

The missing favicon.ico 404 has been fixed.

**Comment by psandtner** [comment] 2019-11-10 16:52
Problem also occurs using Chrome or Firefox:
<img width="912" alt="firefox_console" src="https://user-images.githubusercontent.com/1395629/68547499-8a89cb80-03e2-11ea-826e-30be58c91a24.png">

What the hell is "hastebrot.static.observableusercontent.com"?

I just tried your "redirects"-suggestion. To no avail...

**Comment by danurbanowicz** [comment] 2019-11-10 17:34
It might be worth opening an issue at [netlify/netlify-cms](https://github.com/netlify/netlify-cms) as it's not obvious to me what is causing this error and I'm unable to reproduce it and therefore fix it.

Also check your firewall, ad-blocker, proxy etc if required in case it's something really simple causing the error.

Anyway, if you get any closer to solving this, please let me know!

**Comment by psandtner** [comment] 2019-11-10 17:48
Thanks for your help, Dan! I will probably do that.

**Comment by danurbanowicz** [comment] 2019-11-10 18:01
Also, if you need a temporary fix to this error, you could copy and host the offending module(s) locally in your Netlify project instead of via unpkg.com

**Comment by psandtner** [comment] 2019-11-10 18:23
-import htm from "https://unpkg.com/htm?module";
+import htm from "/admin/preview-templates/htm.js";

in

admin/preview-templates/page.js and
admin/preview-templates/post.js

Preview is working again!

**Comment by danurbanowicz** [comment] 2019-11-11 07:40
OK, good to hear you got a temporary fix working at least.

I'm closing this issue for now but let me know if you want to re-open it.

**Closed by danurbanowicz** 2019-11-11 07:40 UTC
